// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTaAS9tfSgTBpvet3WQUz-kW1_Y1r-0T0',
    appId: '1:86463026904:web:a98be0df0873488ecfa9ad',
    messagingSenderId: '86463026904',
    projectId: 'paintforge-d8cf2',
    authDomain: 'paintforge-d8cf2.firebaseapp.com',
    storageBucket: 'paintforge-d8cf2.firebasestorage.app',
    measurementId: 'G-9BXQ7HNEHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpG491VLn6Ygyz-a-pQaOSbrP5ZoRW1r8',
    appId: '1:86463026904:android:67c1d6b7507eaf5acfa9ad',
    messagingSenderId: '86463026904',
    projectId: 'paintforge-d8cf2',
    storageBucket: 'paintforge-d8cf2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFmDujHlwq-JFQq252PdepLM_oF2XkDGs',
    appId: '1:86463026904:ios:0651204532c2c0bacfa9ad',
    messagingSenderId: '86463026904',
    projectId: 'paintforge-d8cf2',
    storageBucket: 'paintforge-d8cf2.firebasestorage.app',
    iosClientId: '86463026904-bpppnlov2836c7jldsh5b4a3nhbuqtlt.apps.googleusercontent.com',
    iosBundleId: 'com.robermac.paintforge',
  );
}
